#ifndef __SPARTA_CGI_VARIABLES__
#define __SPARTA_CGI_VARIABLES__

#define DECL_VAR(var_name) extern const char* var_name
#define DEF_VAR(var_name) const char* var_name = #var_name

DECL_VAR(HTTP_CACHE_CONTROL);
DECL_VAR(HTTP_CONNECTION);
DECL_VAR(HTTP_CONTENT_LENGTH);
DECL_VAR(HTTP_CONTENT_TYPE);
DECL_VAR(HTTP_ACCEPT);
DECL_VAR(HTTP_ACCEPT_ENCODING);
DECL_VAR(HTTP_ACCEPT_LANGUAGE);
DECL_VAR(HTTP_HOST);
DECL_VAR(HTTP_USER_AGENT);
DECL_VAR(HTTP_DNT);
DECL_VAR(APP_POOL_ID);
DECL_VAR(APP_POOL_CONFIG);
DECL_VAR(APPL_MD_PATH);
DECL_VAR(APPL_PHYSICAL_PATH);
DECL_VAR(AUTH_TYPE);
DECL_VAR(AUTH_PASSWORD);
DECL_VAR(AUTH_USER);
DECL_VAR(CERT_COOKIE);
DECL_VAR(CERT_FLAGS);
DECL_VAR(CERT_ISSUER);
DECL_VAR(CERT_SERIALNUMBER);
DECL_VAR(CERT_SUBJECT);
DECL_VAR(CONTENT_LENGTH);
DECL_VAR(CONTENT_TYPE);
DECL_VAR(DOCUMENT_ROOT);
DECL_VAR(GATEWAY_INTERFACE);
DECL_VAR(HTTPS);
DECL_VAR(HTTPS_KEYSIZE);
DECL_VAR(HTTPS_SECRETKEYSIZE);
DECL_VAR(HTTPS_SERVER_ISSUER);
DECL_VAR(HTTPS_SERVER_SUBJECT);
DECL_VAR(INSTANCE_ID);
DECL_VAR(INSTANCE_NAME);
DECL_VAR(INSTANCE_META_PATH);
DECL_VAR(LOCAL_ADDR);
DECL_VAR(LOGON_USER);
DECL_VAR(PATH_INFO);
DECL_VAR(PATH_TRANSLATED);
DECL_VAR(QUERY_STRING);
DECL_VAR(REMOTE_ADDR);
DECL_VAR(REMOTE_HOST);
DECL_VAR(REMOTE_PORT);
DECL_VAR(REMOTE_USER);
DECL_VAR(REQUEST_METHOD);
DECL_VAR(REQUEST_URI);
DECL_VAR(SCRIPT_FILENAME);
DECL_VAR(SCRIPT_NAME);
DECL_VAR(SERVER_NAME);
DECL_VAR(SERVER_PORT);
DECL_VAR(SERVER_PORT_SECURE);
DECL_VAR(SERVER_PROTOCOL);
DECL_VAR(SERVER_SOFTWARE);
DECL_VAR(URL);
DECL_VAR(__REQUEST_FILE__);

#endif